INSERT INTO "APP"."MODULE" (OID,MODULEID,MODULENAME) VALUES (1,'sv1','User');

INSERT INTO "APP"."GROUP" (OID,GROUPNAME,MODULE_OID) VALUES (1,'Users',1);

INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (1,'John Doe','password','john.doe@mailserver.com',1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (2,'Scott Tiger','password','scott.tiger@mailserver.com',1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (3, 'Ronald Still', 'password', 'rstill12@lucatel.com', 1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (4, 'Ray Herbert', 'password', 'herbert@vesuvio.com', 1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (5, 'Douglas Martin', 'password', 'dmarting@intel.com', 1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (6, 'Adam Hendricks', 'password', 'ahendricks@intel.com', 1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (7, 'Mark Walsh', 'password', 'mealsh@tonins.com', 1);
INSERT INTO "APP"."USER"(OID, USERNAME,PASSWORD,EMAIL,GROUP_OID) VALUES (8, 'James Ning', 'password', 'jning@catuc.com', 1);

INSERT INTO "APP"."CATEGORY" (OID, NAME) VALUES (1, 'Action');
INSERT INTO "APP"."CATEGORY" (OID, NAME) VALUES (2, 'Comedy');
INSERT INTO "APP"."CATEGORY" (OID, NAME) VALUES (3, 'Drama');
INSERT INTO "APP"."CATEGORY" (OID, NAME) VALUES (4, 'Horror');
INSERT INTO "APP"."CATEGORY" (OID, NAME) VALUES (5, 'Sci-FI');

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (1, 'Steven', 'Spielberg','1946-12-18');
INSERT INTO "APP"."ACTOR" (OID,NAME,SURNAME,DATEOFBIRTH) VALUES (1,'Sam','Neil','1947-09-14');
INSERT INTO "APP"."ACTOR" (OID,NAME,SURNAME,DATEOFBIRTH) VALUES (2,'Laura','Dern','1967-02-10');
INSERT INTO "APP"."ACTOR" (OID,NAME,SURNAME,DATEOFBIRTH) VALUES (3,'Jeff','Goldblum','1952-10-22');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (1,'Jurassic Park','1993-09-02',1,1);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (1,1);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (1,2);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (1,3);

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (2,'George','Lucas','1944-05-14');
INSERT INTO "APP"."ACTOR" (OID,NAME,SURNAME,DATEOFBIRTH) VALUES (4,'Mark','Hamill','1951-09-25');
INSERT INTO "APP"."ACTOR" (OID,NAME,SURNAME,DATEOFBIRTH) VALUES (5,'Harrison','Ford','1942-07-13');
INSERT INTO "APP"."ACTOR" (OID,NAME,SURNAME,DATEOFBIRTH) VALUES (6,'Alec','Guinness','1914-04-02');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (2,'Star Wars','1978-02-09',5,2);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (2,4);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (2,5);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (2,6);

INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (7,'Karen','Allen','1951-10-05');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (8,'Alfred','Molina','1953-05-24');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (3,'Raiders of the Lost Ark','1981-10-29',1,1);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (3,5);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (3,7);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (3,8);

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (3,'Sam','Mendes','1965-08-01');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (9,'Kevin','Spacey','1959-07-26');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (10,'Annette','Benning','1958-05-29');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (11,'Thora','Birch','1982-03-11');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (4,'American Beauty','2000-01-20',3,3);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (4,9);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (4,10);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (4,11);

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (4,'Stanley','Kubrick','1928-07-26');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (12,'Jack','Nicholson','1937-04-22');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (13,'Shelley','Duvall','1949-07-07');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (5,'The Shining','1980-10-16',4,4);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (5,12);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (5,13);

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (5,'Martin','Scorsese','1942-11-17');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (14,'Leonardo','DiCaprio','1974-11-11');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (15,'Matt','Damon','1970-10-08');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (16,'Martin','Sheen','1940-08-03');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (6,'The Departed','2006-12-07',3,5);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (6,12);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (6,14);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (6,15);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (6,16);

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (6,'Francis','Ford Coppola','1939-04-07');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (17,'Marlon','Brando','1924-04-03');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (18,'Robert','Duvall','1931-01-05');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (7,'Apocalypse Now','1979-10-04',3,6);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (7,16);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (7,17);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (7,18);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (7,5);

INSERT INTO "APP"."DIRECTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (7,'Harold','Ramis','1944-11-21');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (19,'Bill','Murray','1950-09-21');
INSERT INTO "APP"."ACTOR" (OID, NAME, SURNAME, DATEOFBIRTH) VALUES (20,'Andie','MacDowell','1958-04-21');

INSERT INTO "APP"."MOVIE" (OID,TITLE,RELEASEDATE,CATEGORY_OID,DIRECTOR_OID) VALUES (8,'Groundhog Day','1993-04-29',2,7);

INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (8,19);
INSERT INTO "APP"."MOVIE_ACTOR" (MOVIE_OID,ACTOR_OID) VALUES (8,20);